M48
; DRILL file {KiCad 9.0.6} date 2025-12-21T18:04:32+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-21T18:04:32+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X103.75Y-71.75
X106.29Y-71.75
X123.71Y-71.75
X126.25Y-71.75
T2
X112.92Y-62.0
X115.46Y-62.0
X118.0Y-62.0
T3
X99.0Y-67.5
X131.0Y-67.5
M30
